name: cassandra

ships:
  vagrant-docker: {ip: 10.10.10.30}

services:
  core:
    image: test/core
    instances:
      core:
        ship: vagrant-docker
        ports: {ssh: '22:1000', elasticsearch:  9200, kibana: 80 , consul: 8500}
        lifecycle:
          running: [{type: tcp, port: consul}]
        dns: localhost
